// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaqkewthnacsnkfmiosx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcWtld3RobmFjc25rZm1pb3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjI2NTcsImV4cCI6MjA3MTkzODY1N30.xEMks7V8GOQjF12KQP_GbiZh-RAKiEaZMTlQmGMsYKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});